controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController
    camera_position_controller:
      type: position_controllers/JointGroupPositionController

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    wheel_separation: 0.30
    wheel_radius: 0.0625 
    base_frame_id: "base_link"
    publish_rate: 100.0
    odom_frame_id: "odom"
    use_stamped_vel: false
    enable_odom_tf: false

camera_position_controller:
  ros__parameters:
    joints:
      - camstand_joint
      - cam_joint
    gains:
      camstand_joint: {p: 5.0,  d: 0.5, i: 0.01, i_clamp: 0.5}
      cam_joint:      {p: 3.0,  d: 0.3, i: 0.01, i_clamp: 0.5}
